name: 'Terraform'

on: [push, pull_request]

env:
  TF_LOG: INFO

jobs:
  terraform-validate-test:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: test

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform workspace select
        id: workspace
        run: terraform workspace select test || terraform workspace new test
        continue-on-error: true

      - name: Terraform init test
        id: init
        run: terraform init 
        with:
          args: "-backend-config backends/test.conf"

      - name: Terraform format 
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform validate 
        id: validate
        run: terraform validate
