name: 'Terraform'

on: 
  push:
    branches:
      - main

env:
  TF_LOG: INFO

jobs:
  terraform-validate-test:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: test

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v2

      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: "./terraform"

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./terraform"
          args: "-backend-config=backends/test.conf"
        env:
            TF_WORKSPACE: test

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7

