name: 'Terraform'

on: 
  push:
    branches:
      - main

env:
  TF_LOG: INFO

jobs:
  validate-test:
    uses: ./.github/workflows/terraform-validate.yaml
    with:
      tf_env: test
    environment: test